import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Event from "@/components/Event";

export default function Home({ events }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {events.map((event) => (
          <Event
            key={event.id}
            eventDate={event.eventDate}
            eventStyle={event.eventStyle}
            eventImageUrl={event.eventImageUrl}
            eventHeader={event.eventHeader}
            eventLocation={event.eventLocation}
            eventDetail={event.eventDetail}
          />
        ))}
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const res = await fetch(`${process.env.API_URL}`);
  const events = await res.json();
  return {
    props: {
      events,
    },
  };
};
